Initial release
sunriseos/libfat pull request #1
Opened 2019-07-30 10:49 UTC by Thog

This contains the base implementation of libfat.

2019-07-31 11:24 UTC, Thog commented
Mergeable doesn't want to activate it seems...

2019-08-03 10:41 UTC, roblabla reviewed
Looks good! Here's a few fixes for the docs.

Can be done later, but it'd be nice to add usage docs at the top-level.

2019-08-03 10:41 UTC, roblabla commented on src/attribute.rs
> +    /// Define a device file. SHOULDN'T APPEARS ON DISK.
```suggestion
    /// Define a device file. SHOULDN'T APPEAR ON DISK.
```

2019-08-03 10:41 UTC, roblabla commented on src/directory/dir_entry_iterator.rs
> +                // FIXME: Custom Iterator to catches those errors
```suggestion
                // TODO: Custom Iterator to catches those errors
```

2019-08-03 10:41 UTC, roblabla commented on src/name.rs
> +    /// Permite to extract partial part of the VFAT name and format it to 8.3 name.
```suggestion
    /// Transform VFAT file name into an MSDOS 8.3 filename, taking the first 8 character for the filename, and the first three character after the first dot for the extension. See [ShortFileNameGenerator::create()]
```

2019-08-03 10:41 UTC, roblabla commented on src/cluster.rs
> +//! FAT cluster.
Maybe a few words about what a FAT cluster *is* would be nice here.

2019-08-03 10:41 UTC, roblabla commented on src/directory/dir_entry.rs
> +/// Represent the information of a child entry into in it parent entry.
```suggestion
/// Represents the location information of a child entry in its parent.
```

2019-08-03 10:41 UTC, roblabla commented on src/directory/dir_entry.rs
> +    /// Marker on entries present in the FAT12/FAT16 root directory.
```suggestion
    /// Current entry is in the FAT12/FAT16 root directory.
```

2019-08-03 10:41 UTC, roblabla commented on src/directory/dir_entry.rs
> +    /// The first cluster used for
Stroke alert

2019-08-03 10:41 UTC, roblabla commented on src/directory/dir_entry_iterator.rs
> +                // FIXME: this is dirty
```suggestion
                // TODO: this is dirty
```

2019-08-03 10:41 UTC, roblabla commented on src/directory/mod.rs
> +    // FIXME: better error managment
```suggestion
    // TODO: better error managment
```

2019-08-03 10:41 UTC, roblabla commented on src/directory/mod.rs
> +                // FIXME: is that always the second entry?
```suggestion
                // TODO: is that always the second entry?
```

2019-08-03 10:41 UTC, roblabla commented on src/directory/mod.rs
> +    /// A reference to the filesystem.
```suggestion
    /// A reference to the filesystem containing this directory.
```

2019-08-03 10:41 UTC, roblabla commented on src/directory/mod.rs
> +    /// Open a file a the given path.
```suggestion
    /// Open a file at the given path.
```

2019-08-03 10:41 UTC, roblabla commented on src/directory/mod.rs
> +    /// Search space to allocate a directory entry and return a raw entry iterator to it.
```suggestion
    /// Look for unused space to allocate a directory entry and return a raw entry iterator to it.
```

2019-08-03 10:41 UTC, roblabla commented on src/directory/mod.rs
> +    /// Delete a directory entry in a given parent directory.
```suggestion
    /// Delete a directory entry in a given parent directory.
    ///
    /// # Error
    ///
    /// - `ReadFailed`
    ///    - When the directory is not empty.
```

2019-08-03 10:41 UTC, roblabla commented on src/directory/raw_dir_entry.rs
> +    /// Reint the raw data buffer to a free state.
```suggestion
    /// Reinitialize the raw data buffer to a free state.
```

2019-08-03 10:41 UTC, roblabla commented on src/filesystem.rs
> +/// Reprsent the FS Info structure of FAT32.
```suggestion
/// Represent the FS Info structure of FAT32.
```

2019-08-03 10:41 UTC, roblabla commented on src/filesystem.rs
> +    /// The device device of the filesystem.
```suggestion
    /// The device of the filesystem.
```

2019-08-03 10:41 UTC, roblabla commented on src/filesystem.rs
> +    /// Free a cluster and if specified remove of a cluster chain.
```suggestion
    /// Free a cluster and if specified remove it from a cluster chain.
```

2019-08-16 17:00 UTC, Orycterope requested changes
Reviewed about half of libfat, pushing a first round of comments

2019-08-16 17:00 UTC, Orycterope commented on src/name.rs
> +        short_name[..data.len()].clone_from_slice(&data[..]);
isn't this going to panic if data.len() > 8 + 3 ?

2019-08-16 17:00 UTC, Orycterope commented on src/name.rs
> +    pub const MAX_LEN_UNICODE: usize = Self::MAX_LEN * 4;
Unicode is not an encoding. Did you mean utf8 ? utf16 ? UCS-2 ? 

Why **4** ? Shouldn't it be 2 ?

2019-08-16 17:00 UTC, Orycterope commented on src/name.rs
> +    /// Transform VFAT file name into an MSDOS 8.3 filename, taking the first 8 character for the filename, and the first three character after the first dot for the extension. See [ShortFileNameGene
Add doc.

2019-08-16 17:00 UTC, Orycterope commented on src/table.rs
> +/// Represent a cluster chan value.
```suggestion
/// Represent a cluster chain value.
```

2019-08-16 17:00 UTC, Orycterope commented on src/table.rs
> +    /// Create a new Cluster iteractor starting at ``cluster``.
```suggestion
    /// Create a new Cluster iterator starting at ``cluster``.
```

You should set up a spell checker in your IDE :p

2019-08-16 17:00 UTC, Orycterope commented on src/utils.rs
> +/// This permit to cir
![bsod-windows-8-0x5c-hal-initialization-failed-56a6f9d85f9b58b7d0e5cc3e](https://user-images.githubusercontent.com/6343527/63043791-321f5c80-becd-11e9-9045-61002ead7b94.png)

2019-08-16 17:00 UTC, Orycterope commented on src/utils.rs
> +    let separator_index_opt = path.rfind('/');
Add tests for those cases:

What about `/my_root_dir/my_other_dir/my_child_dir/` ?
What about `my_root_dir/my_other_dir/my_child_file` ?
What about `/` ?
What about ` ` ?

Maybe some of those cases should panic, as you may consider them ill-formed. Then do panic, and document it !

2019-08-16 17:00 UTC, Orycterope commented on src/utils.rs
> +/// Permite to split a path.
Add the same tests, and update the doc

```suggestion
/// Splits a path at the first `/` it encounters.
///
/// Returns a tuple of the parts before and after the cut.
///
/// ```
/// let my_path = "/top_level_dir/middle_dir/sub_dir";
/// let (before, after) = split_path(my_path);
/// assert!(before == "/top_level_dir");
/// assert!(after.unwrap() == "middle_dir/sub_dir");
/// ```
///
/// If no `/` is encountered, the "after" part is None:
///
/// ```
/// let my_path = "/top_level_dir";
/// let (before, after) = split_path(my_path);
/// assert!(before == "/top_level_dir");
/// assert!(after.is_none());
/// ```
///
/// # Panics
/// 
/// @Thog forgot to update the panic conditions
```

2019-08-16 17:00 UTC, Orycterope commented on src/utils.rs
> +/// A simple FileSystemIterator wrapper that implement Iterator
Explain that this enables exposing a core::Iterator instead of our cheap FileSystemIterator type.

2019-08-16 17:00 UTC, Orycterope commented on src/name.rs
> +    pub fn create(context: &mut ShortFileNameContext, lfn: &str) -> ShortFileName {
Explain what you're achieving, and how you're doing it.

This function is 120 lines long with zero comment.

2019-08-16 17:00 UTC, Orycterope commented on src/filesystem.rs
> +struct FatFileSystemInfo {
Should those values only be considered as hints, and used carefully ?
Do you check them yourself when creating the Filesystem, and guarantee they are acurate ?

Document it.

2019-08-16 17:00 UTC, Orycterope commented on src/filesystem.rs
> +        LittleEndian::write_u32(&mut block[0x1e4..0x1e8], 0x6141_7272);
literal strings are more explicit, and consistant with `from_fs`.

2019-08-16 17:00 UTC, Orycterope commented on src/filesystem.rs
> +        let mut block = [0x0u8; crate::MINIMAL_BLOCK_SIZE];
This is fine when you're formatting the disk to FAT, but the rest of the time shouldn't you instead read the block, modify only the concerned fields, and write it back ? Avoiding allocating a full block on the stack every time you flush. 

Or even better, use StorageDevice to only write to the desired bytes ?

2019-08-16 17:00 UTC, Orycterope commented on src/filesystem.rs
> +pub struct FatFileSystem<S: StorageDevice> {
Just for curiosity, why did you choose generics over a `&'a mut dyn StorageDevice` ? :)

2019-08-16 17:00 UTC, Orycterope commented on src/filesystem.rs
> +    // TODO: check we don't go out of the partition
Well, do it.

I don't know if this is what you meant, but you should also ensure `self.partition_size <= self.storage_device.size`.

2019-08-16 17:00 UTC, Orycterope commented on src/lib.rs
> +    InvalidPartition,
What's the difference between this and `PartitionNotFound` ?

2019-08-16 17:00 UTC, Orycterope commented on src/lib.rs
> +            self.fat_type = FatFsType::Fat32;
Wait what ? You determine the type of a FAT partition solely based on its cluster count ?

2019-08-16 17:00 UTC, Orycterope commented on src/lib.rs
> +    pub(crate) fn set_valid(&mut self, fat_type: FatFsType) {
This is confusing, you have both `fat_type` passed as an argument, and `self.fat_type`. What happens when they're not the same ?

The only place where you use this function is in `format_partition`. The fact that it takes `&mut self` is weird. I believe this should be a constructor, change it to
```suggestion
    pub(crate) fn create(fat_type: FatFsType) -> FatVolumeBootRecord {
```
allocate an empty block, prefill the desired fields, return it, and let `format_partition` fill the remaining fields. 

This removes the need for a `new_unchecked` constructor.

2019-08-16 17:00 UTC, Orycterope commented on src/lib.rs
> +            self.fat_size32()
A `FatVolumeBootRecord` is aware of its own type. You should use it to know where to read, instead of trying to guess.

2019-08-16 17:00 UTC, Orycterope commented on src/lib.rs
> +                            * u64::from(fs.boot_record.bytes_per_block()),
Wait, shouldn't this be **self**.backup_boot_record_block() ?

This is really confusing, as `fs.boot_record` should also be `self`, but you pass both as parameters. If they ever don't match, we unleash hell.

I believe you shouldn't take the rich `FatFileSystem` type which is our owner here. Just take the StorageDevice, the partition start, and write there, based solely on **our** boot_record.

2019-08-16 17:00 UTC, Orycterope commented on src/lib.rs
> +    let boot_record = FatVolumeBootRecord::new(block);
As `FatVolumeBootRecord::new` is only used here, the two function could definitely be merged together into a "read" constructor for FVBR: 
```
fn FatVolumeBootRecord::read(storage_device, partition_start) -> Result<Self>
``` 

This eliminates boiler-plate error handling.

2019-08-16 17:00 UTC, Orycterope commented on src/lib.rs
> +) -> FatFileSystemResult<FatFileSystem<S>> {
We shouldn't do partitions like that. `parse_fat_boot_record` should be fed a StorageDevice that spans the partition, and nothing else.

The way it works should be similar to [`split_at_mut`](https://doc.rust-lang.org/std/primitive.slice.html#method.split_at_mut) on slices: 
We create a function in fs that takes a BlockDevice, consumes it, and spits out two BlockDevices, where each one internally knows its partition start and end, and translates offsets when writing to the disk.

In theory this is safe, for the same reason `split_at_mut` is safe: the two BlockDevices represent non-overlapping sections of the disks. They share a handle to the disk however, but this is ok. I just don't know for now how to manage the drop of the handle, and linking the lifetimes seems tedious. 

It becomes a real problem if we choose to also share the cache, as this would require to put a Mutex around the LRU since both partitions can access it simultaneously. I think having a LRU for each partition is not unreasonable, and a lot easier. 
Because of this, we might want to only implement it on a really low-level AHCI disk wrapper, instead of generically on every BlockDevice.

With this in place we can make sure fs-drivers, including FAT, cannot possibly write outside of their own partition, and it simplifies a lot of things for them, as they don't have to track and always add their partition start/end every time they do a read or write.

2019-08-16 17:00 UTC, Orycterope commented on src/lib.rs
> +            let mut file_system = FatFileSystem::new(
Hey, check everything fits in the partition we have, and sections don't overlap themselves, if this can happen.

2019-08-16 17:00 UTC, Orycterope commented on src/lib.rs
> +                file_system.init()?;
What is this `uninitialized` boolean parameter ? Document it.

2019-08-16 17:00 UTC, Orycterope commented on src/lib.rs
> +        // If we have too many clusters, try to make it in range of the FAT12
You forgot ExFat

2019-08-16 17:00 UTC, Orycterope commented on src/lib.rs
> +        // If we have too many clusters, try to make it in range of the FAT12
Pretty much everywhere in this function apparently. This is why we use `match` :p 

Add a 
```
if let FatFsType::ExFat = fat_type {
    unimplemented!();
}
```
at the start of the function.

2019-08-16 17:00 UTC, Orycterope commented on src/filesystem.rs
> +            Ok(self.get_root_directory())
Document that getting the parent of `"/"` will succeed and give back `"/"` again.

2019-08-16 17:00 UTC, Orycterope commented on src/filesystem.rs
> +            self.get_root_directory().open_directory(parent_name)
Why don't you use `open_directory` ?

This is incompatible with `get_parent("/")` returning `""`, where `open_directory` expects `"/"`, but this might not be the best design for `get_parent`.

2019-08-16 17:00 UTC, Orycterope commented on src/filesystem.rs
> +        parent_new_dir.rename(old_entry, file_name, is_dir)
Does this remove it from `parent_old_dir` ?

2019-08-16 17:00 UTC, Orycterope commented on src/filesystem.rs
> +        parent_new_dir.rename(old_entry, file_name, is_dir)
Is `rename("/same/path", "/same/path", _)` safe ?

2019-08-16 17:00 UTC, Orycterope commented on src/filesystem.rs
> +        parent_new_dir.rename(old_entry, file_name, is_dir)
You need to check for a folder being moved to a child of itself:
`rename("/a/b", "/a/b/c", true)` is invalid, as there is no longer any path to `c` after that.

2019-08-16 17:00 UTC, Orycterope commented on src/filesystem.rs
> +        parent_new_dir.rename(old_entry, file_name, is_dir)
You need to think about `"/"` rename:
`rename("/a/b/c", "/", true)` would fail I guess, since destination (`"/"`) already exists.
`rename("/", "/a/b/c", true)` falls in the "move a folder into itself" problem, I guess.

2019-08-17 00:51 UTC, Thog commented on src/name.rs
> +    pub const MAX_LEN_UNICODE: usize = Self::MAX_LEN * 4;
in this context it means 'Unicode Scalar Value' as defined in rust char documentation.

The max size used by that is a 32 bits value that's why I multiply it by 4.

2019-08-17 00:54 UTC, Thog commented on src/filesystem.rs
> +pub struct FatFileSystem<S: StorageDevice> {
The idea is that FatFileSystem is supposed to be the only one owning the StorageDevice. Also worth noting that all methods in StorageDevice take a mutable ref to self.

2019-08-17 00:54 UTC, Thog commented on src/filesystem.rs
> +    // TODO: check we don't go out of the partition
oops outdated comment, it's already the case

2019-08-17 00:56 UTC, Thog commented on src/lib.rs
> +            self.fat_type = FatFsType::Fat32;
That's how you should do it by Microsoft specs...
![image](https://user-images.githubusercontent.com/1760003/63204675-9c392c80-c09a-11e9-82e2-796803d5f718.png)

2019-08-17 00:58 UTC, Thog commented on src/lib.rs
> +            self.fat_size32()
the legacy fields can be used on newer iteration of FAT so this is needed sadly.

2019-08-17 00:59 UTC, Thog commented on src/lib.rs
> +                file_system.init()?;
for format

2019-08-17 01:00 UTC, Thog commented on src/lib.rs
> +        // If we have too many clusters, try to make it in range of the FAT12
I should probably just remove the value for ExFat as it cannot be constructed and will not be actually used so well

2019-08-17 12:03 UTC, roblabla commented on src/name.rs
> +    pub const MAX_LEN_UNICODE: usize = Self::MAX_LEN * 4;
"when represented as an array of unicode scalar values".

2019-08-17 12:38 UTC, Thog commented on src/name.rs
> +    /// Transform VFAT file name into an MSDOS 8.3 filename, taking the first 8 character for the filename, and the first three character after the first dot for the extension. See [ShortFileNameGene
?

2019-08-17 12:53 UTC, Thog commented on src/filesystem.rs
> +        let mut block = [0x0u8; crate::MINIMAL_BLOCK_SIZE];
The whole 512 bytes should be cleared as every data in it is defined as reserved except the signatures and the two cluster informations.

2019-08-17 12:54 UTC, Thog commented on src/filesystem.rs
> +    // TODO: check we don't go out of the partition
For future reference: the check must be done by the StorageDevice.

2019-08-17 12:56 UTC, Thog commented on src/lib.rs
> +    InvalidPartition,
PartitionNotFound is only used in get_partition (Function that take a StorageDevice and parse the MBR table to find a partition at the given index)

2019-08-17 13:03 UTC, Thog commented on src/lib.rs
> +    pub(crate) fn set_valid(&mut self, fat_type: FatFsType) {
The self.fat_type refer to a cached value that isn't initialized during format.

This function only write signatures based on the given fat_type. The fat_type is determined during the formatting so I cannot do a create function containing the entire initialization of the FatVolumeBootRecord.

2019-08-20 12:19 UTC, Orycterope commented on src/filesystem.rs
> +        let mut block = [0x0u8; crate::MINIMAL_BLOCK_SIZE];
Well, ok

2019-08-20 15:45 UTC, Orycterope requested changes
Pretty much done reviewing libfat.

2019-08-20 15:45 UTC, Orycterope commented on src/directory/mod.rs
> +            lowercase_name.push(c.to_lowercase().next().unwrap());
No.

Some characters lowercase to multiple characters:
```
// Sometimes the result is more than one character:
assert_eq!('İ'.to_lowercase().to_string(), "i\u{307}");
```
if a protected `/i` file exists, you can unlawfully write to it by opening `/İ` instead, let libfat convert it, and fs won't catch it.

2019-08-20 15:45 UTC, Orycterope commented on src/directory/mod.rs
> +            }
copying here is tedious.

You should instead check when you're instantiating a directory entry that its name is all lowercase. Otherwise the entry should be considered malformed.

Comparing names then becomes much easier.

2019-08-20 15:45 UTC, Orycterope commented on src/directory/mod.rs
> +    pub(crate) fn search_entry(&self, path: &str) -> FatFileSystemResult<DirectoryEntry> {
```
/// **Recursively** search for an entry in the current directory and its children
``` 
?

2019-08-20 15:45 UTC, Orycterope commented on src/directory/mod.rs
> +        loop {
You don't need to loop here. `search_entry` should be responsible for the recursion.

You can split the path into a "dir" and "file" parts by
```rust
let (parent_dir: Directory, filename: &str) = match utils::get_parent(path) {
    ("", filename) => { 
        // we are the parent dir
        (Directory::from_entry(self.fs, self.dir_info), path)
            
    },
    (parent_path, filename) => {
        (self.search_entry(parent_path), filename)
    }
};
```

let `search_entry` deal with the directory traversing, and focus only on the file part. 

Same goes for the `open_directory` function.

2019-08-20 15:45 UTC, Orycterope commented on src/directory/mod.rs
> +            return Err(FatError::PathTooLong);
lowercase the name, check it still fits, and store it lowercased.

2019-08-21 11:51 UTC, roblabla commented on src/name.rs
> +    pub fn create(context: &mut ShortFileNameContext, lfn: &str) -> ShortFileName {
Webarchive link please.

2019-08-22 08:02 UTC, Thog commented on src/lib.rs
> +) -> FatFileSystemResult<FatFileSystem<S>> {
This need more work on storage_device, might be a good idea to make it an issue for the next release.

2019-08-22 16:46 UTC, roblabla approved these changes

2019-08-22 16:46 UTC, roblabla commented on src/cluster.rs
> +        let first_block_of_cluster = (self.0 - 2) * u32::from(fs.boot_record.blocks_per_cluster());
- Can `self.0` ever be 0 or 1? If so, this can panic.
- Similarly, `self.0 - 2 * u32::from(blahblahblah)` might panic. Cast to u64 early.
- If fs.first_data_offset is oob, same issue.

As much as possible, we should either:

- Use wrapping/checked/overflowing operations
- Cast to larger data types early.

2019-08-22 16:46 UTC, roblabla commented on src/directory/mod.rs
> +/// Represent a Directory.
```suggestion
/// Represents a Directory.
```

2019-08-22 16:46 UTC, roblabla commented on src/directory/mod.rs
> +/// Represent a File.
```suggestion
/// Represents a File.
```

2019-08-22 16:46 UTC, roblabla commented on src/directory/mod.rs
> +    /// Create a custom version of this directory referencing to "." .
```suggestion
    /// Create a custom version of this directory, using the name "." .
```

2019-08-22 16:46 UTC, roblabla commented on src/directory/mod.rs
> +    /// Create a custom version of this directory referencing to ".." .
```suggestion
    /// Create a custom version of this directory, using the name ".." .
```

2019-08-24 17:15 UTC, Orycterope approved these changes

2019-08-24 18:20 UTC, merged